### ISSUE TITLE
DeprecationWarning from test_combo_field_icon_formatter

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#527] opened 2020-06-01 16:45 UTC
There's a `DeprecationWarning` from the `test_combo_field` tests on Python 3.8.

```
test_combo_field_icon_formatter (pyface.fields.tests.test_combo_field.TestComboField) ... /Users/mdickinson/.venvs/traits/lib/python3.8/site-packages/pkg_resources/__init__.py:1156: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  return get_provider(package_or_requirement).get_resource_string(
ok
```

**Comment by DiddiLeija** [comment] 2021-06-29 17:27
Hello, I would like to take this issue (if no one's on it). What do I have to do?

**Comment by rahulporuri** [comment] 2021-06-30 11:19
Thanks for showing interest in contributing to pyface @DiddiLeija . This issue though might be outdated/closed already. The deprecation warning is coming from `pkg_resources` and we don't use `pkg_resources` in pyface anymore - we replaced its usage with `importlib_resources` and `importlib_metadata`.

I'm closing this issue as I am unable to reproduce it locally.

If you're interested @DiddiLeija , you can look at some other issues labeled "good first issue" in the pyface or other ETS repositories.

**Closed by rahulporuri** 2021-06-30 11:19 UTC
Labels: Good First Issue, component: test suite, difficulty: easy
