### ISSUE TITLE
from pyface.base_toolkit import Toolkit, find_toolkit ModuleNotFoundError: No module named 'pyface.base_toolkit'

### ISSUE THREAD

**Issue by lucascbarbosa** [enthought/pyface#941] opened 2021-05-10 19:16 UTC
I'm having this issue: 
```
 from pyface.base_toolkit import Toolkit, find_toolkit
ModuleNotFoundError: No module named 'pyface.base_toolkit'
```

**Comment by rahulporuri** [comment] 2021-05-11 03:12
Thanks for opening the issue @lucascbarbosa .

Can you give us some information about the machine you are working on : 
- OS type and version
- Python vendor
- Python version
- Are you using virtual environments or a third-party python distribution (e.g. edm, conda, active state python etc)?
- TraitsUI version and PyFace version (preferably just provide the full list of packages installed in the python environment)
- Did you install TraitsUI and/or PyFace from git source or via PyPI or via the third-party python vendor?
- What is on your path (`path`/`PATH` environment variable) when you run the python script that produces this error?

That information will help us identify the root cause of the issue that you are running into.

**Comment by rahulporuri** [comment] 2021-05-12 01:45
@lucascbarbosa can you destroy the conda environment and recreate it from scratch?

**Comment by rahulporuri** [comment] 2021-05-12 01:54
>  It is also raised when `None` is found in `sys.modules`.

Ref https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError. Can you tell us what the output of `python -c "import sys; print(sys.modules)"`?

**Comment by lucascbarbosa** [comment] 2021-05-12 02:16
False!

**Comment by mdickinson** [comment] 2021-05-12 09:44
@lucascbarbosa I've pasted an interpreter session below. Please could you show what you get for the equivalent session on your machine? (It's really helpful if you copy and paste the exact results, including full tracebacks - those tracebacks contain a lot of potentially useful information that can help us to debug your issue.)

```python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.13 |Enthought, Inc. (x86_64)| (default, Apr 13 2021, 19:22:11) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import traitsui
>>> traitsui
<module 'traitsui' from '/Users/mdickinson/.edm/envs/test/lib/python3.6/site-packages/traitsui/__init__.py'>
>>> traitsui.__version__
'7.1.1'
>>> import pyface
>>> pyface
<module 'pyface' from '/Users/mdickinson/.edm/envs/test/lib/python3.6/site-packages/pyface/__init__.py'>
>>> pyface.__version__
'7.3.0'
>>> import pyface.base_toolkit
```

**Comment by lucascbarbosa** [comment] 2021-05-12 16:16
```python
Python 3.6.13 (default, Feb 19 2021, 05:17:09) [MSC v.1916 64 bit (AMD64)] on win32    
>>> import traitsui
<module 'traitsui' from 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\traitsui\\__init__.py'>
'7.1.1'
>>> import pyface                                                                     
>>> pyface
<module 'pyface' from 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\tvtk\\pyface\\__init__.py'>
>>> pyface.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyface' has no attribute '__version__'
>>> import pyface.base_toolkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyface.base_toolkit'
```

**Comment by mdickinson** [comment] 2021-05-13 12:19
Thank you! It looks as though `pyface` is being picked up from the wrong place: you want `pyface` from the `site-packages` directory rather than from `site-packages/tvtk`.  At a guess, somehow the `site-packages/tvtk` directory has made it into your `sys.path`, possibly as a result of a packaging error in the conda package for Mayavi. (If I test with EDM, I do indeed see a `tvtk.pyface` subpackage, but the `tvtk` directory isn't on sys.path, and so `import pyface` picks up the correct pyface version.)

**Comment by mdickinson** [comment] 2021-05-13 13:18
The next debugging steps would be to print the `sys.path`. E.g:
```python
>>> import sys
>>> sys.path
['', '/Users/mdickinson/.edm/envs/test/lib/python36.zip', '/Users/mdickinson/.edm/envs/test/lib/python3.6', '/Users/mdickinson/.edm/envs/test/lib/python3.6/lib-dynload', '/Users/mdickinson/.edm/envs/test/lib/python3.6/site-packages']
```

and to double check the current working directory, for example with:
```
>>> import os
>>> os.getcwd()
'/Users/mdickinson'
```

That would confirm the hypothesis that `sys.path` is being modified somehow. But I'm afraid if that's the case, we can't help much with figuring out how - it definitely isn't Pyface doing the sys.path modification. At this point this is fairly clearly a Python environment / packaging issue rather than a Pyface issue.

**Comment by lucascbarbosa** [comment] 2021-05-13 13:22
I tried to delete pyface from tvtk/ directory, but it's still necessary since the following bug appeared:
```
  File "simulate.py", line 17, in <module>
    from sfepy.postprocess.viewer import Viewer
  File "C:\Users\lucas\anaconda3\envs\deeplearn\lib\site-packages\sfepy\postprocess\viewer.py", line 27, in <module>
    from tvtk.pyface.scene_editor import SceneEditor
ModuleNotFoundError: No module named 'tvtk.pyface'
```

**Comment by mdickinson** [comment] 2021-05-13 13:25
Yes, the code in `tvtk/pyface` is necessary. The bug is that it shouldn't be being picked up by an `import pyface`. The import mechanism is complicated, but the search order is mostly governed by the `PYTHONPATH` environment variable and the `sys.path` list, so examining those would be the next step.

**Comment by lucascbarbosa** [comment] 2021-05-13 13:29
```python
import sys
>>> sys.path
['', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\tvtk', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\python36.zip', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\DLLs', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn', 'C:\\Users\\lucas\\AppData\\Roaming\\Python\\Python36\\site-packages', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\sfepy-2021.1+git.127ab753a2f4f24ed359d0152088d11227c3dd49-py3.6-win-amd64.egg', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\pymesh2-0.3-py3.6-win-amd64.egg', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\win32', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\win32\\lib', 'C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\Pythonwin']
```

**Comment by rahulporuri** [comment] 2021-05-18 10:56
closing as this isn't really an issue with the package. also closing the related issue in traitsui.

> Even removing the `PYTHONPATH` at `./tvtk`, the output from `sys.path` still has `C:\\Users\\lucas\\anaconda3\\envs\\deeplearn\\lib\\site-packages\\tvtk`

You can try updating `sys.path` in your script i.e. at the very top of your script, remove the tvtk site-packages path and then see if `pyface` works as expected.

**Closed by rahulporuri** 2021-05-18 10:56 UTC
