### ISSUE TITLE
DataView widget disappears from UI when embedded in a tab

### ISSUE THREAD

**Issue by xamcost** [enthought/pyface#786] opened 2020-10-23 17:07 UTC
Hi there ! I am experiencing a UI issue when trying to use the `DataView` widget. When I include it in a UI with a tab, it disappears if I switch focus to another tab.

Two implementations were tried to include `DataView` in my traitsui `View`. Either embedding it in a traitsui `CustomEditor`, to be then placed in a ```UItem('data_model', editor=DataModelEditor(), style='custom')```:

```Python3
def _data_view_factory(parent, editor):
    """ Returns the Qt Widget corresponding to the editor. """
    widget = DataViewWidget(
        data_model=editor.value,
    )
    editor._widget = widget
    widget._create()
    return widget.control


class DataModelEditor(CustomEditor):

    #: Overwrite the parent class trait to include a default
    #: factory
    factory = Callable(_data_view_factory)

```

or either subclassing `traitsui.qt4.editor.Editor` and `traitsui.api.EditorFactory` (in a a dirty way, I admit it), such as in the following snippet:

```Python3
class MyEditor(Editor):

    def init(self, parent):
        widget = DataViewWidget(
            data_model=self.value,
        )
        widget._create()
        self.control = widget.control

    def update_editor(self):
        self.control._widget.data_model = self.value


class MyEditorFactory(EditorFactory):

    def simple_editor(self, ui, obj, name, description, parent):
        return MyEditor(parent, factory=self, ui=ui,
                        object=obj,
                        name=name,
                        description=description)
```

Any idea what's happening ?

Thanks in advance for your help !

**Comment by pedrorivotti** [comment] 2020-10-26 19:08
I'd just like to contribute to @xamcost 's issue by providing a more complete minimal example that shows the problem, and a possible workaround. Hopefully this will also provide some clues for a more permanent solution to this issue.

-----------

### Minimal example

To replicate, run the code below, switch to tab "B", and back to tab "A". Notice the DataView widget disappearing after switching back to "A". 

```python
from traits.api import Callable, HasTraits, Str
from traitsui.api import CustomEditor, Group, View, Item
from pyface.data_view.data_view_widget import DataViewWidget

def _data_view_factory(parent, editor):
    widget = DataViewWidget()
    widget._create()
    return widget.control

class MyEditor(CustomEditor):
    factory = Callable(_data_view_factory)

class MyView(HasTraits):
    a = Str()
    b = Str()
    def default_traits_view(self):
        return View(
            Group(
                Item("a", editor=MyEditor(), style="custom"),
                Item("b"),
                layout="tabbed",
            )
        )

MyView().configure_traits()
```

### Possible workaround

Use a `QTimer` with a small enough interval (100ms in the example below), to keep forcing the widget to be shown.

```python
from traits.api import Callable, HasTraits, Str
from traitsui.api import CustomEditor, Group, View, Item
from pyface.data_view.data_view_widget import DataViewWidget
from pyface.qt import QtCore

def _data_view_factory(parent, editor):
    widget = DataViewWidget()
    widget._create()

    timer = QtCore.QTimer(parent=widget.control)
    timer.setInterval(100)
    timer.timeout.connect(widget.control.show)
    timer.start()

    return widget.control

class MyEditor(CustomEditor):
    factory = Callable(_data_view_factory)

class MyView(HasTraits):
    a = Str()
    b = Str()
    def default_traits_view(self):
        return View(
            Group(
                Item("a", editor=MyEditor(), style="custom"),
                Item("b"),
                layout="tabbed",
            )
        )

MyView().configure_traits()

```

### Packages in the environment
```
appdirs            1.4.3-1   enthought/free
distribute_remove  1.0.0-4   enthought/free
icu4c              50.2-2    enthought/free
libjpeg            7.0-5     enthought/free
libpng             1.6.36-5  enthought/free
libxml2            2.9.7-1   enthought/free
libxslt            1.1.30-1  enthought/free
packaging          16.8-4    enthought/free
pip                20.0.2-2  enthought/free
pyface             7.1.0-1   enthought/free
pygments           2.2.0-1   enthought/free
pyparsing          2.2.0-1   enthought/free
pyqt5              5.14.2-3  enthought/free
pyqt5_sip          12.7.2-1  enthought/free
qt                 5.12.6-6  enthought/free
setuptools         41.6.0-4  enthought/free
six                1.15.0-1  enthought/free
traits             6.1.1-1   enthought/free
traitsui           7.1.0-1   enthought/free
```

Tested on macOS 10.15.7

**Comment by xamcost** [comment] 2020-10-27 09:21
@pedrorivotti Thanks a lot, it works and greatly helps !

**Comment by corranwebster** [comment] 2020-11-13 09:16
When I look at the minimal example, I'm getting a lot of errors to the console of the form:
```
Error in rowCount
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/test-data-view-tabs/lib/python3.6/site-packages/pyface/ui/qt4/data_view/data_view_item_model.py", line 121, in rowCount
    if self.model.can_have_children(row_index):
AttributeError: 'NoneType' object has no attribute 'can_have_children'
Error in columnCount
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/test-data-view-tabs/lib/python3.6/site-packages/pyface/ui/qt4/data_view/data_view_item_model.py", line 132, in columnCount
    if self.model.can_have_children(row_index):
AttributeError: 'NoneType' object has no attribute 'can_have_children'
```
because there is no data model.  One fix coming out of this is that the `DataViewWidget` should not allow `None` for the model.

This is making me think, however, that the problem may not be that the widget is not hiding, but that it is not demanding enough space.

**Comment by pedrorivotti** [comment] 2020-11-13 09:47
@corranwebster Sorry for the errors, my attempt at a minimal example was perhaps too minimal, and I agree that the errors can distract from the actual issue. However, those errors are not at the centre of the issue reported here, since the problem was initially observed in a codebase with a more complete implementation, where model was not `None`.

Here is another example:
```python
from pyface.data_view.api import AbstractDataModel, DataViewWidget
from pyface.data_view.value_types.api import NumericValue
from traits.api import Callable, HasTraits, Str
from traitsui.api import CustomEditor, Group, View, Item


class MyModel(AbstractDataModel):

    def can_have_children(self, row):
        return True

    def get_column_count(self):
        return 1

    def get_row_count(self, row):
        return 1

    def get_value(self, row, column):
        return 1

    def get_value_type(self, row, column):
        return NumericValue()

def _data_view_factory(parent, editor):
    widget = DataViewWidget(data_model=MyModel())
    widget._create()
    return widget.control

class MyEditor(CustomEditor):
    factory = Callable(_data_view_factory)

class MyView(HasTraits):
    a = Str()
    b = Str()
    def default_traits_view(self):
        return View(
            Group(
                Item("a", editor=MyEditor(), style="custom"),
                Item("b"),
                layout="tabbed",
            )
        )

MyView().configure_traits()
```

**Comment by corranwebster** [comment] 2020-11-13 09:51
> This is making me think, however, that the problem may not be that the widget is not hiding, but that it is not demanding enough space.

It appears not: forcing a minimum size and setting an expanding size policy aren't fixing things.

Another things which isn't quite right in the example is that the parent widget isn't set, but I think that's not the issue here (setting it doesn't fit things).  We should have something like the following in the factory:
```
    if isinstance(parent, QtGui.QLayout):
        parent = parent.parentWidget()
    widget.parent = parent
```
That was a plausible cause as well, but it doesn't seem to fix things.

**Comment by pedrorivotti** [comment] 2020-11-13 09:54
> Another thing which isn't quite right in the example is that the parent widget isn't set,

Thanks, I'll update the minimal example in the issue description.

**Comment by corranwebster** [comment] 2020-11-13 09:58
Aha!  It's not a dataview problem, it's a more general Pyface widget problem.  The following factory also exhibits the problem:
```

def _field_factory(parent, editor):
    widget = TextField()
    if isinstance(parent, QtGui.QLayout):
        parent = parent.parentWidget()
    widget.parent = parent
    widget._create()
    editor._widget = widget
    return widget.control
```

**Comment by corranwebster** [comment] 2020-11-13 10:00
I am now suspicious of this code: https://github.com/enthought/pyface/blob/fbfee5062bdfbe1a9c1102f0d3390eaf8227e9da/pyface/ui/qt4/widget.py#L105-L127

**Comment by corranwebster** [comment] 2020-11-13 10:10
I am almost certain that the problem is that this line:
https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/widget.py#L125
should be
```
             widget.visible = widget.control.isHidden() 
```
and possibly there should be a few other places where we need to be careful about `visible` vs. `hidden` state.

**Comment by corranwebster** [comment] 2020-11-13 10:50
OK, here is a work-around which you can use which fixes the immediate problem (not guaranteeing 100% correct, but it seems to work).

First, here is the fixed event filter class
```
from pyface.qt import QtCore


class WidgetEventFilter(QtCore.QObject):
    """ An internal class that watches for certain events on behalf of the
    Widget instance.
    """

    def __init__(self, widget):
        """ Initialise the event filter. """
        QtCore.QObject.__init__(self)
        self._widget = widget

    def eventFilter(self, obj, event):
        """ Adds any event listeners required by the window. """
        widget = self._widget
        # Sanity check.
        if obj is not widget.control:
            return False

        event_type = event.type()

        if event_type == QtCore.QEvent.Show:
            widget.visible = True
        
        elif event_type == QtCore.QEvent.Hide and widget.control.isHidden():
            widget.visible = False

        return False
```

Second, you need to replace the default `_event_filter` with the fixed one _before_ calling `_create()`:
```
def _data_view_factory(parent, editor):
    widget = DataViewWidget(data_model=MyModel())
    if isinstance(parent, QtGui.QLayout):
        parent = parent.parentWidget()
    widget.parent = parent
    widget._event_filter = WidgetEventFilter(widget)
    widget._create()
    return widget.control
```

I'll open a couple of new issues that have come out of this: one to fix the visibility issue, one to fix the empty model problem.

**Comment by xamcost** [comment] 2020-11-13 10:52
Got it, thanks a lot for investigating the problem @corranwebster !

**Closed** 2020-11-18 13:07 UTC
Labels: type: bug
